version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region region | docker login --username AWS --password-stdin 123456789012.dkr.ecr.region.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t todos-apprunner .
      - docker tag todos-apprunner:latest 123456789012.dkr.ecr.region.amazonaws.com/todos-apprunner:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 123456789012.dkr.ecr.region.amazonaws.com/todos-apprunner:latest

