# Used by AWS CodeBuild to build and push the Docker image to Amazon ECR
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 594989874014.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t todos-apprunner .
      - docker tag todos-apprunner:latest 594989874014.dkr.ecr.us-east-1.amazonaws.com/todos-apprunner:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 594989874014.dkr.ecr.us-east-1.amazonaws.com/todos-apprunner:latest
